version: "3.8"

services:

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - ENV_VARIABLE_1=value1
      - ENV_VARIABLE_2=value2
      - METAPASTE=https://pokepast.es/dc1eac2d8740c97b
    # This creates interactive mode which lets us execute commands in a shell when the container is running. 
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_SERVER_PORT=8080
      - PUBLIC_SERVER_HOST=http://backend
    stdin_open: true
    tty: true
    depends_on:
      - backend

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  #nginx:
  #  image: nginx
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #  networks:
  #    - my-network

#networks:
#  my-network:
#    driver: bridge


    
    
